### (1)
아래와 같은 dict 타입의 값이 주어질 때,   
value의 순서에 따라 key의 순서로 이루어진 리스트를 반환하는 함수 구현   
value 값이 같은 경우 key 값의 사전 순서에 따라 정렬

예시)   
함수 입력값: {'a': 10, 'b': 15, 'c': 15, 'd': 0, 'e': 5}   
함수 반환값: ['d', 'e', 'a', 'b', 'c']

In [18]:
# 함수
def sort_dict(d):
    sorted_list = []
    # 내용
    
    return sorted_list

In [5]:
import sys

def sort_dict(d):
    sorted_list = []
    
    list_dict = []
    for key, value in d.items():
        list_dict.append([value, key])
#     print(list_dict)
    list_dict.sort()
#     print(list_dict)
#     sys.exit()
    for val in list_dict:
        sorted_list.append(val[1])
    
    return sorted_list

# 실행문
data_dict = {'apple': 10, 'banana': 5, 'cake': 15, 'desert': 35,
            'egg': 30, 'fruit': 15, 'grape': 50, 'ham': 25}

print(sort_dict(data_dict))
# 수행 결과: ['banana', 'apple', cake', 'fruit', 'ham', 'egg', 'desert', 'grape']

[[10, 'apple'], [5, 'banana'], [15, 'cake'], [35, 'desert'], [30, 'egg'], [15, 'fruit'], [50, 'grape'], [25, 'ham']]
[[5, 'banana'], [10, 'apple'], [15, 'cake'], [15, 'fruit'], [25, 'ham'], [30, 'egg'], [35, 'desert'], [50, 'grape']]

SystemExit:

### (2)
주어진 list 데이터를 dict 형태로 변환하여 반환하는 함수 구현   
list는 '도서명', 가격 순으로 나열되어 있음   
1) 도서명이 없는 경우: list에서 몇번째 자료인지 출력. dict에 저장하지 않음   
2) 가격이 문자형인 경우: int로 형변환 후 dict에 저장

예시)   
함수 입력값: ['a', 10, 'b', 15, 'c', 15, 'd', 20, 'e', 5]   
함수 반환값: {'a': 10, 'b': 15, 'c': 15, 'd': 20, 'e': 5}

예시-1)
함수 입력값: ['a', 10, '', 15, 'c', 15, 'd', 20, 'e', 5]   
출력: '2번째 도서명 미기입'

In [ ]:
# 함수
def list2dict(l):
    re_dict = {}
    # 내용
    
    return re_dict

In [8]:
import sys

def list2dict(l):
    re_dict = {}
    
    for i in range(0, len(l), 2): # 0, 2, 4, 6 ...
        if l[i] == '':
            print(f'{int(i/2) + 1}번째 도서명 미기입')
            continue
        
        re_dict[l[i]] = int(l[i + 1])
    
    return re_dict

# 실행문
data_list = ['롤랑의 노래', 19800, '7년의 밤', '14500', '달 샤베트', 12000, 
             '', 13800, '백광', '14500']

print(list2dict(data_list))
# 수행 결과: 
# 4번째 도서명 미기입
# {'롤랑의 노래': 19800, '7년의 밤': 14500, '달 샤베트': 12000, '백광': 14500}

4번째 도서명 미기입
{'롤랑의 노래': 19800, '7년의 밤': 14500, '달 샤베트': 12000, '백광': 14500}

In [16]:
import sys
import numpy as np

def list2dict(l):
    re_dict = {}
    
    l = np.array(l)
    l = np.reshape(l, (-1, 2))
    
    for idx, item in enumerate(l):
        if item[0] == '':
            print(f'{idx + 1}번째 도서명 미기입')
            continue
        
        re_dict[item[0]] = int(item[1])
    return re_dict

# 실행문
data_list = ['롤랑의 노래', 19800, '7년의 밤', '14500', '달 샤베트', 12000, 
             '', 13800, '백광', '14500']

print(list2dict(data_list))
# 수행 결과: 
# 4번째 도서명 미기입
# {'롤랑의 노래': 19800, '7년의 밤': 14500, '달 샤베트': 12000, '백광': 14500}

4번째 도서명 미기입
{'롤랑의 노래': 19800, '7년의 밤': 14500, '달 샤베트': 12000, '백광': 14500}

In [19]:
a = [10, 20, 30, 40, 50]

for idx, val in enumerate(a):
    print(idx, val)

0 10
1 20
2 30
3 40
4 50

### (3)
도서 현황 리스트를 관리하는 클래스 구현하기

클래스 선언 시, list 자료형을 매개변수로 넣으며   
list에는 각 책에 대한 (책제목, 작가명, 가격, 보유 장서 수)가 들어있음

1) constructor을 사용하여 list로 입력된 정보를 books 변수에 list와 dict를 사용하여 정리   
예시)   
입력: [('롤랑의 노래', '-', 19800, 6), ...]   
books: [{name: '롤랑의 노래', 'author': '-', 'cost': 19800, 'count': 6}, ...]

2) 총 보유 장서 수를 출력하는 함수 구현   
3) 총 보유 장서의 가치를 출력하는 함수 구현   
가치는 '가격 * 보유 장서 수'로 계산 함    
4) 조건 입력 시 해당되는 조건의 책 제목을 출력하는 함수 구현. 조건은 '이름 부등호 값'으로 작성됨
예시)   
'cost > 16000'   
"author == '김초엽'"

In [ ]:
class manageBooks:
    def __init__(self, list_books):
        self.books = []
    
    def countBook( ... ):  # 입력 파라미터 없음
        ...
        return ... # type int
    
    def costBook( ... ): # 입력 파라미터 없음
        ...
        return ... # type int
    
    def search( ... ): # str 입력
        ...
        return ...  # type list # ['책제목 1', '책제목 2', ...]

In [33]:
import sys

class manageBooks:
    def __init__(self, list_books):
        self.books = []
        
        for info in list_books:
            name, author, cost, count = info # ('롤랑의 노래', '-', 19800, 6)
            
            book = {
                'name': name,
                'author': author,
                'cost': cost,
                'count': count
            }
            self.books.append(book)
    
    def countBook(self):  # 입력 파라미터 없음
        count_sum = 0
        for book in self.books:
            count_sum += book['count']
        return count_sum
    
    def costBook(self): # 입력 파라미터 없음
        cost_sum = 0
        for book in self.books:
            cost_sum += book['cost'] * book['count']
        return cost_sum
    
    def search(self, condi): # str 입력
        co_book = []
        
        for book in self.books:
            name, author, cost, count, = book['name'], book['author'], book['cost'], book['count']
            if eval(condi):
                co_book.append(name)

#         condi = condi.split(' ') # ['cost', '>', '16000']
#         if condi[1] == '>': # >= == != < <=
#             for book in self.books:
#                 if book[condi[0]] > int(condi[2]):
#                     co_book.append(book['name'])
#         elif condi[1] == '>=':
#             ...
                    
#         print(condi)
#         sys.exit()
        
        return co_book # type list # ['책제목 1', '책제목 2', ...]

# 실행문
list_book = [('롤랑의 노래', '-', 19800, 6),
             ('7년의 밤', '정유정', 14500, 3),
             ('달 샤베트', '백희나', 12000, 11),
             ('달러구트 꿈 백화점', '이미예', 13800, 14),
             ('백광', '렌조 미키히코', 14500, 7),
             ('지구 끝의 온실', '김초엽', 15000, 11),
             ('이기적 유전자', '리처드 도킨스', 20000, 8),
             ('파과', '구병모', 14000, 6),
             ('긴긴밤', '루리', 11500, 4),
             ('방구석 미술관', '조원재', 16800, 9)]

manage_books = manageBooks(list_book)
# print(manage_books.countBook()) # 79
# print(manage_books.costBook()) # 1195200
print(manage_books.search('cost > 16000'))
# ['롤랑의 노래', '이기적 유전자', '방구석 미술관']
print(manage_books.search("author == '김초엽'")) # ['지구 끝의 온실']

['롤랑의 노래', '이기적 유전자', '방구석 미술관']
['지구 끝의 온실']

### (4)
숫자 단위를 변형하는 클래스 구현하기

선언 시 클래스가 가질 값과 단위(m, km)를 설정하며(각 변수명은 value. unit 사용),   
직접 값에 접근해 출력하는 것이 불가능하게 함(print(클래스.value) 사용 불가)   
아래처럼 함수를 선언함

1) m를 km로 변환하는 함수, 변환된 값을 클래스내 저장   
예시)   
24000, 'm' -> 24, 'km'   
'm'가 아닌 경우 변화 없음   
2) km를 m로 변환하는 함수, 변환된 값을 클래스내 저장   
예시)   
2, 'km' -> 2000, 'm'   
'km'가 아닌 경우 변화 없음   
3) 클래스 내 저장된 값을 단위를 더하여 str 형태로 출력하는 함수
예시)   
24000, 'm' -> '24,000m'   
단위가 ' '인 경우 ' ' 반환   
4) setter 데코레이터를 사용하여, 클래스 내 저장된 값이나 단위를 바꿀 때 다음을 적용함   
* 값을 바꿀 때 음수를 넣을 경우 0으로 변환하여 저장   
* 'm', 'km' 이외의 단위를 넣는 경우 빈문자 ' '로 변환하여 저장   
예시)   
 -5000 -> 0    
 'cm' -> ' '


* 모든 값은 소수점 아래 4자리에서 반올림하여 사용

In [ ]:
class Converter:
    def __init__(self, value, unit):
        self.__value = value
        self.__unit = unit
        
    # decorator를 사용하여 4) 구현
        
    def cToM( ... ):
        ... 
    
    def cToKm( ... ):
        ...
    
    def printValue( ... ):
        ...
        return ... # type str

In [44]:
import sys

value = 123456.00001

strV = list(str(value))
strV.reverse()

retV = []

for idx, v in enumerate(strV):
    if idx > 0 and idx % 3 == 0:
        retV.append(',')
    retV.append(v)

retV.reverse()
print(''.join(retV))

123,456,.00,001

In [5]:
import sys

value = 12345.00001

strV = list(str(value))
strV.reverse()

retV = []

if '.' in strV:
    split_idx = strV.index('.')
    retV.extend(strV[:split_idx + 1]) # 10000.
    strV = strV[split_idx + 1 : ]

for idx, v in enumerate(strV):
    if idx > 0 and idx % 3 == 0:
        retV.append(',')
    retV.append(v)

retV.reverse()
print(''.join(retV))

12,345.00001

In [6]:
import sys

class Converter:
    def __init__(self, value, unit):
        self.__value = value
        self.__unit = unit
        
    @property
    def value(self):
        return self.__value
    @value.setter
    def value(self, val):
        if val < 0:
            val = 0
        self.__value = val
        
    @property
    def unit(self):
        return self.__unit
    @unit.setter
    def unit(self, unit):
        if unit not in ['m', 'km']:
            unit = ''
        self.__unit = unit
    
        
    def cToM(self):
        if self.__unit != 'km':
            return
        self.__value = self.__value * 1000
        self.__unit = 'm'
    
    def cToKm(self):
        if self.__unit != 'm':
            return
        self.__value = round(self.__value / 1000, 3)
        self.__unit = 'km'
    
    def printValue(self):
        if self.__unit == '':
            return ''
        
        strV = list(str(self.__value))
        strV.reverse()

        retV = []

        if '.' in strV:
            split_idx = strV.index('.')
            retV.extend(strV[:split_idx + 1])
            strV = strV[split_idx + 1 : ]

        for idx, v in enumerate(strV):
            if idx > 0 and idx % 3 == 0:
                retV.append(',')
            retV.append(v)

        retV.reverse()
        return ''.join(retV) + ' ' + self.__unit

# 실행문
metric = Converter(1000, 'm')
print(metric.printValue()) # 1,000 m

metric.cToKm()
print(metric.printValue()) # 1.0 km

metric.value = 300
metric.unit = 'm'
print(metric.printValue()) # 300 m

metric.value = -50
print(metric.printValue()) # 0 m

metric.unit = 'cm'
print(metric.printValue()) # ''

1,000 m
1.0 km
300 m
0 m

### (5)
(4)에서 구현한 클래스를 상속하기

단위 mile를 추가 적용.   
(4)에서 선언한 함수가 변형되지 않도록 상속하여 사용   

(4)의 1), 2) 함수가 mile에 대해서도 제 기능을 하도록   
아래와 같이 변형함

1) m, mile을 km로 변환하는 함수, 변환된 값을 클래스내 저장   
예시)   
24000, 'm' -> 24, 'km'   
'm', 'mile'이 아닌 경우 변화 없음   
2) km, mile를 m로 변환하는 함수, 변환된 값을 클래스내 저장   
예시)   
2, 'km' -> 2000, 'm'   
'km', 'mile'이 아닌 경우 변화 없음   


아래 함수를 추가로 구현함   
5) m, km를 mile로 변환하는 함수. 변환된 값을 클래스내 저장   
예시)   
2, 'km' -> 1.243, 'mile'   
'm', 'km'가 아닌 경우 변화 없음   

* 1 mile = 1.609 km 로 계산(소수점 아래 4자리에서 반올림하여 사용)
* 4)의 setter 가능은 제거한 Converter 클래스 사용

In [7]:
class Converter:
    def __init__(self, value, unit):
        self.value = value
        self.unit = unit
        
    def cToM(self):
        if self.unit != 'km':
            return
        self.value = self.value * 1000
        self.unit = 'm'
    
    def cToKm(self):
        if self.unit != 'm':
            return
        self.value = round(self.value / 1000, 3)
        self.unit = 'km'
    
    def printValue(self):
        if self.unit == '':
            return ''
        
        strV = list(str(self.value))
        strV.reverse()

        retV = []

        if '.' in strV:
            split_idx = strV.index('.')
            retV.extend(strV[:split_idx + 1])
            strV = strV[split_idx + 1 : ]

        for idx, v in enumerate(strV):
            if idx > 0 and idx % 3 == 0:
                retV.append(',')
            retV.append(v)

        retV.reverse()
        return ''.join(retV) + ' ' + self.unit

In [13]:
class Converter_2(Converter):
    def __init__(self, value, unit):
        super().__init__(value, unit)
        
    def cToM(self):
        if self.unit == 'km':
            self.value = self.value * 1000
        elif self.unit == 'mile':
            self.value = self.value * 1.609 # mile to km
            self.value = self.value * 1000 # km to m
        
        self.value = round(self.value, 3)
        self.unit = 'm'
    
    def cToKm(self):
        if self.unit == 'm':
            self.value = self.value / 1000
        elif self.unit == 'mile':
            self.value = self.value * 1.609 # mile to km
        
        self.value = round(self.value, 3)
        self.unit = 'km'
    
    def cToMile(self): 
        if self.unit == 'm':
            self.value = self.value / 1000 # m to km
            self.value = self.value / 1.609 # km to mile
        elif self.unit == 'km':
            self.value = self.value / 1.609 # km to mile
        
        self.value = round(self.value, 3)
        self.unit = 'mile'

In [14]:
# 실행문
metric = Converter_2(1000, 'm')
print(metric.printValue()) # 1,000 m

metric.cToMile()
print(metric.printValue()) # 0.622 mile

metric.value = 300
metric.cToM()
print(metric.printValue()) # 482,700.0 m

metric.cToKm()
print(metric.printValue()) # 482.7 km

1,000 m
0.622 mile
482,700.0 m
482.7 km